### ISSUE TITLE
CONFIG_ZRAM_LZ4_COMPRESS

### ISSUE THREAD

**Issue by Dazzworld** [xiaomi-msm8998/kernel_xiaomi_msm8998#1]
https://github.com/xiaomi-msm8998/kernel_xiaomi_msm8998/commit/6849209303f878627de373d23bb3882fbbdd531b

https://github.com/xiaomi-msm8998/kernel_xiaomi_msm8998/commit/1548f7cdd361b99b2625a00c9692db6c9502254f

Maybe CONFIG_ZRAM_LZ4_COMPRESS should be replaced with CONFIG_CRYPTO_LZ4?

**Comment by ArianK16a** [comment]
You are right. Thanks!

**Comment by ArianK16a** [comment]
Fixed on lineage-16.0 branch. 9.x will stay as backup for now.
